### ISSUE TITLE
Contributors and Maintainers welcome

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#20]
Hi!

Thank you @real-yfprojects for your contribution in #3 and #18 
Would you like to co-author and co-maintain this project?, you'd be more than welcome!
...then I would add you on github.

thx
Johannes

**Comment by real-yfprojects** [comment]
I'd be interested. I am still catching up on the last few weeks. Oh btw I like you coding style.

**Comment by johannesjh** [comment]
Thank you... I added you as collaborator! br, Johannes
