### ISSUE TITLE
Run tests in a matrix of python versions and system architectures

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#30]
Suggested enhancement: Automated tests could be run in a matrix for different architectures and python versions:
* system architectures: x86_64, aarch64
* python versions, e.g., cp37 through to cp311

Tooling, possible solutions: 

* test runtime on github ci:
  * Using the matrix feature of github actions to define a matrix of architectures and python versions
  * Using quemu emulation for aarch64 using https://github.com/uraimo/run-on-arch-action
  * The tests could be started directly by invoking python unittest, or indirectly via tox with the `skip_missing_interpreters` option.

* test runtime for local testing: 
  * GNOME Builder can run cross platform builds using quemu
  * Tox with the `skip_missing_interpreters` option

**Comment by johannesjh** [comment]
Not sure if we need this. And the ci is already quite complex... I think we could just leave the ci tests as is.

**Comment by real-yfprojects** [comment]
A matrix of python versions will be useful and easy to setup. I never worked on this issue because of the arm request.

**Comment by johannesjh** [comment]
hm ok, I guess we could ignore ARM for now.

**Comment by johannesjh** [comment]
I'd opt for closing this issue.

**Comment by real-yfprojects** [comment]
fine with me
