### ISSUE TITLE
Announce the project over on gnome discourse

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#31]
https://discourse.gnome.org/t/req2flatpak-a-new-script-for-generating-flatpak-build-modules-to-package-python-apps-using-flatpak/12285?u=johannesjh

**Comment by real-yfprojects** [comment]
> I found that req2flatpak runs much faster than req2flatpak

Found a typo.

**Comment by johannesjh** [comment]
thx, I fixed it.
