### ISSUE TITLE
classmethod build_module_as_str is untested?

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#45]
AFAICT, the actual command line tool doesn't run `build_module_as_str`.  Nor does `pytest`.

(I tried putting an `assert False` in there and nothing has triggered it yet).

In #41, I'm adding `build_module_as_yaml_str`, which is similarly untested.

- - - -

I guess the command line tool should run these classmethods intead, except they are designed to return strings and the command-line tool is based on streams.

**Comment by johannesjh** [comment]
Hi, thank you for your analysis. Yes, you are right... the commandline tool should use the classmethod instead of calling `json.dump(build_module, output_stream, indent=4)`.

**Comment by johannesjh** [comment]
Fixed in #41
