### ISSUE TITLE
use yaml comments to note "generated by req2flatpak"

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#47]
For example, some other tool does this:
```
# Generated with flatpak-pip-generator requests-toolbelt==0.10.1 --yaml
name: python3-requests-toolbelt
buildsystem: simple
build-commands:
```

That's pretty helpful when you review an old file as it includes exactly the command line used to build it.

Even without the full command line, it would still be helpful to note where the file came from

**Comment by cbm755** [comment]
I did a quick fix for this on top of my `yaml` branch.  Useful?

Note pyyaml does not support comments so I just write it into the stream manually.

**Comment by real-yfprojects** [comment]
> Useful?

I like that! What about a link to the repo? I know other tools don't do that, but I imagine it to be useful.

**Comment by johannesjh** [comment]
I like this proposition, too. (I would rather not link to the repo because the script typically won't know which repo or fork it was taken from).
