### ISSUE TITLE
Contributors and Maintainers welcome

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#52]
Hi @cbm755 

I would like to thank you for contributing to this project in your past pull requests.

Would you like to co-author and co-maintain this project?, you'd be more than welcome!
...then I would add you on github as a collaborator.

thx
Johannes

**Comment by real-yfprojects** [comment]
@cbm755 Me too. You are currently the most active contributor. Initially I was planning on contributing more to *req2flatpak* but I don't have much time lately since one of my other projects is participating in GSoC.

**Comment by cbm755** [comment]
Not sure I'll always have time, but happy to help.

In general, I think many maintainers is good, as folks can be more or less active over time.

**Comment by johannesjh** [comment]
awesome, thank you! I added/invited you as collaborator in this project. (and yes, we can all be more or less active over time, I guess we are all juggling multiple projects and responsibilities).
