### ISSUE TITLE
Let's release a v0.2

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#53]
There have been many improvements during the past few months, thanks to @cbm755 and @real-yfprojects, which means we could release a new version.

* [x] I tagged issues and merge requests with [v0.2](https://github.com/johannesjh/req2flatpak/milestone/1) in github's issue tracker. This makes it easy to see what has changed since v0.2
* [x] We probably should start writing release notes. Let's determine a simple format, e.g., a `Release Notes.rst` file that we include into the documentation. It would be nice if these release notes could show up in pypi as well. See #54 
* [x] We could (should?) bump dependency versions using `poetry update`, just to keep things up to date. See #55
* [x] We should test a release candidate, e.g., by using it in our projects 
* [x] We can then publish a release by following the documentation, i.e., tagging a commit is all that is needed to publish to pypi

**Comment by real-yfprojects** [comment]
Should the release notes contain only changes to `req2flatpak.py` or also changes to the dev setup, ...?

> * It would be nice if these release notes could show up in pypi as well

We can add the file to the `tools.poetry.readme` list.

**Comment by real-yfprojects** [comment]
This release basically includes a bug fix (#39) and yaml support.

**Comment by johannesjh** [comment]
Yes, essentially one feature (yaml support) and two bugfixes (#34 and #39).

**Comment by johannesjh** [comment]
I created an initial draft of the changelog in merge request #54. feedback, corrections, improvements etc are of course welcome!

**Comment by johannesjh** [comment]
To test the code before its release, I started using the latest version of req2flatpak in [favagtk](https://gitlab.gnome.org/johannesjh/favagtk/-/commit/b045904875debc30fa353e6d4f8b6a9d0ffcedc7)

UPDATE:
favagtk's autoupdate script [ran successfully](https://gitlab.gnome.org/johannesjh/favagtk/-/jobs/2863543) using the new version of req2flatpak.

**Comment by johannesjh** [comment]
I think we are ready for releasing a v0.2.0, following our own instructions for [publishing a release](https://johannesjh.github.io/req2flatpak/main/development.html#publishing-a-release).

I submitted pull request #60 to prepare for the release.

**Comment by johannesjh** [comment]
done, we published v0.2
