### ISSUE TITLE
Disable Wiki and add tags

### ISSUE THREAD

**Issue by real-yfprojects** [johannesjh/req2flatpak#56]
Let's disable the wiki page in the settings of this repo. We don't need it.

Let's also add tags to the repo to improved discoverability. E.g. when searching `flatpak generate` or `flatpak generate manifest` this repo won't show up.

**Comment by johannesjh** [comment]
I disabled the wiki and added some "topics" to the project's "about" metadata.

![Screenshot_20230418_173447_Firefox](https://user-images.githubusercontent.com/581188/232828681-764bf951-f45e-4ccc-b919-e4f56a5ba480.jpg)

**Comment by cbm755** [comment]
Please capitalize "Python" and "Flatpak" in the description. 

Suggestion: "A script ..." is not so relevant.  How about:

> Convert Python package requirements to Flatpak build manifests

Bikeshedding much?  sorry!

**Comment by johannesjh** [comment]
Thank you, I updated and improved the project description using your suggestion.

**Comment by real-yfprojects** [comment]
Maybe add `script` to tags?
