### ISSUE TITLE
docs: fix bullet lists by adding trailing whitespace

### ISSUE THREAD

**Issue by johannesjh** [johannesjh/req2flatpak#57]
I noticed these aren't rendered as bullet lists since they are missing trailing whitespace (for some reason github's renderer doesn't care):

https://github.com/johannesjh/req2flatpak/blob/847406f3afabee316059f3a484466c70651541a8/docs/source/development.rst?plain=1#L29-L33

_Originally posted by @real-yfprojects in https://github.com/johannesjh/req2flatpak/issues/55#issuecomment-1512657372_

**Comment by johannesjh** [comment]
Bulleted lists are broken in many (if not all) places in the documentation. 

For example, here as screenshots of the README, as rendered by github, correctly rendered with bullets:
![bulletlists rendered correctly by github](https://user-images.githubusercontent.com/581188/232843480-192d3076-ff0a-4eda-8c4b-24ed4a58c703.png)

... and the same content rendered by sphinx, broken without bullets:
![bulletlists broken rendering in sphinx](https://user-images.githubusercontent.com/581188/232843456-40d71431-9ee7-44c6-8d34-4ae3c69ee414.png)

**Comment by real-yfprojects** [comment]
Yes its basically everywhere. Adding a trailing line after each bullet point should fix it.

**Comment by johannesjh** [comment]
Adding newlines between the bullet points did not work.

I found this stackoverflow question: https://stackoverflow.com/q/67542699
The answers suggest that it is a bug in sphinx-rtd-theme
