### ISSUE TITLE
Error - Specify version as 'package==version'

### ISSUE THREAD

**Issue by EvilSupahFly** [johannesjh/req2flatpak#69]
So, I have my `requirements.txt` file, which has some packages listed as `package>=version` which is normally fine. However, req2flatpak seems to want fixed package numbers (`package==version`). Is that by design, or just an oversight?

**Comment by cbm755** [comment]
I think that's by design: `req2flatpak` is not a dependency resolver.

**Comment by cbm755** [comment]
Here's what is says in the docs:

>  ...whereas req2flatpak.py asks the user to provide a fully resolved list of dependencies with frozen dependency versions. Various tools exist which make this easy, e.g., pip, pip-compile and poetry.

https://johannesjh.github.io/req2flatpak/main/introduction.html#related-work
